client_connection:
  client_listen_IP: "127.0.0.1" # The IP address the backend listens for the client on
  port: 54321

backend_connection:
  backend_IP: "127.0.0.1" # The IP address the backend listens for the webserver on
  port: 65432

que_size: 5
machinery: "proxmox"

scan_directory: "/server/backend/scans"